Add test report to workflow

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -34,3 +34,13 @@ jobs:
       run: pnpm install
     - name: Build 
       run: pnpm build
+    - name: Unit tests
+      run: pnpm test
+
+    - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()        # run this step even if previous step failed
+        with:
+          name: JEST Tests                # Name of the check run which will be created
+          path: .artifacts/vitest*.xml    # Path to test results
+          reporter: jest-junit            # Format of test results
